repo: http://github.com/eshoo/mdscom
services:
  - frontend:
      install_script:
        - npm install .
      test_script:
        - npm test
      language: nodejs
      nodejs:
        - 0.10
      propeller:
        ports:
          FRONTEND_HTTP: 8000 
          MYSQL: 3306
        services:
          - postgres
      heroku:
        app: mdscom
  - backend:
      language: nodejs
      propeller:
        instances: 1
      heroku:
        app: mdscom
